spring:
  application:
    name: my-springboot-seed
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    cache-names:
    - ${spring.application.name}
seed:
  seed-name: ${spring.application.name}
  jwt:
    secret: 201807181234
    expireIn: 1728000 #20Days
    token:
      header: Authorization
      type: Bearer
      length: 7
    prefix:
      auth: Auth
      user: UserDetail
  validate-code:
    image:
      urls: /auth/register,/auth/code/email,/auth/code/sms
      expire-in: 600
    email:
      urls: /auth/submitResetPwdEmail
      expire-in: 600
      length: 8
    sms:
      urls: /auth/submitResetPwdPhone
      expire-in: 600
      length: 4
      mobile-max-send-count: 1
      ip-max-send-count: 2
      total-max-send-count: 3
      
      